<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>to_do_list</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestRunner.cs" />
    <Compile Include="TestProgram.cs" />
    <Compile Include="TodoItem.cs" />
    <Compile Include="Patterns\Adapter.cs" />
    <Compile Include="Patterns\AsyncAwait.cs" />
    <Compile Include="Patterns\BackgroundWorker.cs" />
    <Compile Include="Patterns\Command.cs" />
    <Compile Include="Patterns\Composite.cs" />
    <Compile Include="Patterns\Decorator.cs" />
    <Compile Include="Patterns\Factory.cs" />
    <Compile Include="Patterns\ProducerConsumer.cs" />
    <Compile Include="Patterns\ReaderWriterLock.cs" />
    <Compile Include="Patterns\Singleton.cs" />
  </ItemGroup>

</Project>